language: perl
env:
  - IN_TRAVIS=1 AUTHOR_TESTING=1
perl:
  - "5.24"
  - "5.22"
  - "5.18"
  - "5.16"
  - "5.10"
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
