language: perl
install:
  - cpanm -n -q --skip-satisfied --installdeps .
before_script:
  - cpanm -n -q --skip-satisfied
script:
  - perl Build.PL && ./Build && ./Build test
perl:
  - "5.24"
  - "5.22"
  - "5.18"
  - "5.16"
  - "5.10"
